// Package main implements the gscompile CLI tool — the GoScript 2.0 compiler
// entry point. It reads .gs files (Go syntax) and compiles them to JavaScript.
package main

import (
	"bufio"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/davidjeba/goscript/pkg/gscompiler"
)

// Version is the compiler version, set at build time via -ldflags.
var Version = "2.0.0"

const banner = "// Generated by goscript v2.0 — https://github.com/davidjeba/goscript"

func main() {
	// Flag definitions
	var (
		output  string
		watch   bool
		version bool
		dir     string
		minify  bool
	)

	flag.StringVar(&output, "o", "", "output file path (default: stdout)")
	flag.StringVar(&output, "output", "", "output file path (default: stdout)")
	flag.BoolVar(&watch, "w", false, "watch mode: recompile on file changes (stub)")
	flag.BoolVar(&watch, "watch", false, "watch mode: recompile on file changes (stub)")
	flag.BoolVar(&version, "v", false, "print version and exit")
	flag.BoolVar(&version, "version", false, "print version and exit")
	flag.StringVar(&dir, "d", "", "compile all .gs files in a directory")
	flag.StringVar(&dir, "dir", "", "compile all .gs files in a directory")
	flag.BoolVar(&minify, "minify", false, "minify JavaScript output")

	flag.Usage = func() {
		fmt.Fprintf(os.Stderr, "gscompile — GoScript 2.0 Compiler\n\n")
		fmt.Fprintf(os.Stderr, "Usage:\n")
		fmt.Fprintf(os.Stderr, "  gscompile [flags] <file.gs> [file2.gs ...]\n")
		fmt.Fprintf(os.Stderr, "  gscompile [flags]               (read from stdin)\n\n")
		fmt.Fprintf(os.Stderr, "Flags:\n")
		flag.PrintDefaults()
		fmt.Fprintf(os.Stderr, "\nExamples:\n")
		fmt.Fprintf(os.Stderr, "  gscompile app.gs                  # compile to stdout\n")
		fmt.Fprintf(os.Stderr, "  gscompile -o bundle.js app.gs     # compile to file\n")
		fmt.Fprintf(os.Stderr, "  gscompile -d ./src                # compile directory\n")
		fmt.Fprintf(os.Stderr, "  gscompile --minify -o out.js a.gs b.gs  # minify output\n")
	}

	flag.Parse()

	// Handle version flag
	if version {
		fmt.Printf("gscompile v%s\n", Version)
		os.Exit(0)
	}

	// Handle watch mode (stub)
	if watch {
		fmt.Fprintln(os.Stderr, "gscompile: watch mode is not yet implemented")
		fmt.Fprintln(os.Stderr, "Watch mode will recompile .gs files on change in a future release.")
		os.Exit(0)
	}

	// Determine input sources
	var files []string

	if dir != "" {
		// Directory mode: find all .gs files
		gsFiles, err := findGSFiles(dir)
		if err != nil {
			fmt.Fprintf(os.Stderr, "gscompile: error scanning directory: %s\n", err)
			os.Exit(1)
		}
		if len(gsFiles) == 0 {
			fmt.Fprintf(os.Stderr, "gscompile: no .gs files found in %s\n", dir)
			os.Exit(1)
		}
		files = gsFiles
	} else if flag.NArg() > 0 {
		// File arguments
		files = flag.Args()
	} else {
		// Stdin mode
		source, err := readStdin()
		if err != nil {
			fmt.Fprintf(os.Stderr, "gscompile: error reading stdin: %s\n", err)
			os.Exit(1)
		}
		if strings.TrimSpace(source) == "" {
			fmt.Fprintln(os.Stderr, "gscompile: no input (pass .gs files or pipe to stdin)")
			os.Exit(1)
		}

		js, err := compileSource(source, "<stdin>")
		if err != nil {
			printError("<stdin>", err)
			os.Exit(1)
		}

		if minify {
			js = minifyJS(js)
		}

		if err := writeOutput(output, banner+"\n\n"+js); err != nil {
			fmt.Fprintf(os.Stderr, "gscompile: %s\n", err)
			os.Exit(1)
		}
		return
	}

	// Compile each file and concatenate output
	var allJS strings.Builder
	allJS.WriteString(banner)
	allJS.WriteString("\n\n")

	for _, file := range files {
		if !strings.HasSuffix(file, ".gs") {
			fmt.Fprintf(os.Stderr, "gscompile: warning: skipping non-.gs file: %s\n", file)
			continue
		}

		source, err := os.ReadFile(file)
		if err != nil {
			fmt.Fprintf(os.Stderr, "gscompile: error reading %s: %s\n", file, err)
			os.Exit(1)
		}

		js, err := compileSource(string(source), file)
		if err != nil {
			printError(file, err)
			os.Exit(1)
		}

		if len(files) > 1 {
			allJS.WriteString(fmt.Sprintf("// --- %s ---\n", filepath.Base(file)))
		}
		allJS.WriteString(js)
		allJS.WriteString("\n\n")
	}

	result := strings.TrimRight(allJS.String(), "\n") + "\n"
	if minify {
		result = minifyJS(result)
	}

	if err := writeOutput(output, result); err != nil {
		fmt.Fprintf(os.Stderr, "gscompile: %s\n", err)
		os.Exit(1)
	}
}

// compileSource runs the full compile pipeline: lex → parse → generate.
func compileSource(source, filename string) (string, error) {
	// Lex
	lexer := gscompiler.NewLexer(source)
	tokens, err := lexer.Tokenize()
	if err != nil {
		return "", fmt.Errorf("lexer error in %s: %w", filename, err)
	}

	// Parse
	parser := gscompiler.NewParser(tokens)
	program, err := parser.Parse()
	if err != nil {
		return "", fmt.Errorf("%s: %w", filename, err)
	}

	// Generate
	generator := gscompiler.NewGenerator()
	javascript, err := generator.Generate(program)
	if err != nil {
		return "", fmt.Errorf("generator error in %s: %w", filename, err)
	}

	return javascript, nil
}

// printError displays compilation errors with source position context.
func printError(filename string, err error) {
	msg := err.Error()

	// If the error already contains position info from the parser (e.g. "file:3:5: msg"),
	// display it directly. Otherwise, prefix with the filename.
	if strings.Contains(msg, filename) {
		fmt.Fprintf(os.Stderr, "gscompile: %s\n", msg)
	} else {
		fmt.Fprintf(os.Stderr, "gscompile: %s: %s\n", filename, msg)
	}

	// Try to show surrounding source lines for context
	line, col := extractPosition(msg)
	if line > 0 {
		source := readSourceForContext(filename)
		if source != "" {
			showSourceContext(source, line, col)
		}
	}
}

// extractPosition attempts to extract line and column from an error message.
// It looks for patterns like ":3:5:" or ":3:" in the error string.
func extractPosition(msg string) (line, col int) {
	re := regexp.MustCompile(`:(\d+):(\d+):`)
	matches := re.FindStringSubmatch(msg)
	if len(matches) == 3 {
		fmt.Sscanf(matches[1], "%d", &line)
		fmt.Sscanf(matches[2], "%d", &col)
		return
	}

	re2 := regexp.MustCompile(`:(\d+):`)
	matches2 := re2.FindStringSubmatch(msg)
	if len(matches2) == 2 {
		fmt.Sscanf(matches2[1], "%d", &line)
		col = 0
	}
	return
}

// readSourceForContext reads the source file for error display context.
func readSourceForContext(filename string) string {
	if filename == "<stdin>" {
		return ""
	}
	data, err := os.ReadFile(filename)
	if err != nil {
		return ""
	}
	return string(data)
}

// showSourceContext prints the offending source line with a pointer.
func showSourceContext(source string, line, col int) {
	scanner := bufio.NewScanner(strings.NewReader(source))
	currentLine := 0
	var targetLine string
	for scanner.Scan() {
		currentLine++
		if currentLine == line {
			targetLine = scanner.Text()
			break
		}
	}

	if targetLine == "" {
		return
	}

	fmt.Fprintf(os.Stderr, "  %s\n", targetLine)
	if col > 0 {
		padding := col - 1
		if padding < 0 {
			padding = 0
		}
		fmt.Fprintf(os.Stderr, "  %s^\n", strings.Repeat(" ", padding))
	}
}

// writeOutput writes the compiled JavaScript to stdout or a file.
func writeOutput(path, content string) error {
	if path == "" {
		_, err := fmt.Print(content)
		return err
	}

	// Ensure parent directory exists
	dir := filepath.Dir(path)
	if dir != "" && dir != "." {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("could not create output directory: %w", err)
		}
	}

	return os.WriteFile(path, []byte(content), 0644)
}

// readStdin reads all input from stdin until EOF.
func readStdin() (string, error) {
	stat, err := os.Stdin.Stat()
	if err != nil {
		return "", err
	}

	// Check if stdin is a terminal (no piped input)
	if stat.Mode()&os.ModeCharDevice != 0 {
		return "", nil
	}

	data, err := io.ReadAll(os.Stdin)
	if err != nil {
		return "", err
	}
	return string(data), nil
}

// findGSFiles recursively finds all .gs files in a directory,
// sorted alphabetically for deterministic output order.
func findGSFiles(dir string) ([]string, error) {
	var files []string

	err := filepath.WalkDir(dir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() && strings.HasSuffix(d.Name(), ".gs") {
			files = append(files, path)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}

	sort.Strings(files)
	return files, nil
}

// minifyJS performs simple whitespace-based minification on JavaScript output.
// It removes leading/trailing whitespace per line, collapses blank lines,
// and trims the overall output.
func minifyJS(js string) string {
	var result strings.Builder
	prevBlank := false

	scanner := bufio.NewScanner(strings.NewReader(js))
	for scanner.Scan() {
		line := scanner.Text()

		// Strip inline comments (simple: // to end of line, but not inside strings)
		trimmed := strings.TrimSpace(line)

		// Skip blank lines
		if trimmed == "" {
			if !prevBlank {
				result.WriteString("\n")
				prevBlank = true
			}
			continue
		}

		// Strip single-line comments
		if strings.HasPrefix(trimmed, "//") {
			continue
		}

		// Remove leading indentation
		result.WriteString(trimmed)
		result.WriteString("\n")
		prevBlank = false
	}

	return strings.TrimRight(result.String(), "\n") + "\n"
}
